# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logiciel_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 533)
        MainWindow.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_test)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 2, 1)
        self.configure_box = QtWidgets.QGroupBox(self.tab_test)
        self.configure_box.setObjectName("configure_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.configure_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.configure_toolbox_layout = QtWidgets.QHBoxLayout()
        self.configure_toolbox_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.configure_toolbox_layout.setSpacing(6)
        self.configure_toolbox_layout.setObjectName("configure_toolbox_layout")
        self.bus_combobox = QtWidgets.QComboBox(self.configure_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_combobox.sizePolicy().hasHeightForWidth())
        self.bus_combobox.setSizePolicy(sizePolicy)
        self.bus_combobox.setObjectName("bus_combobox")
        self.configure_toolbox_layout.addWidget(self.bus_combobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.configure_toolbox_layout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.configure_toolbox_layout)
        self.configure_stackedwidget = QtWidgets.QStackedWidget(self.configure_box)
        self.configure_stackedwidget.setObjectName("configure_stackedwidget")
        self.verticalLayout_6.addWidget(self.configure_stackedwidget)
        self.gridLayout.addWidget(self.configure_box, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_button = QtWidgets.QPushButton(self.tab_test)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(self.tab_test)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.start_button = QtWidgets.QPushButton(self.tab_test)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_data)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.tab_data)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plotCanvas = MplCanvas(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotCanvas.sizePolicy().hasHeightForWidth())
        self.plotCanvas.setSizePolicy(sizePolicy)
        self.plotCanvas.setObjectName("plotCanvas")
        self.verticalLayout_3.addWidget(self.plotCanvas)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.data_combo = QtWidgets.QComboBox(self.groupBox)
        self.data_combo.setFrame(True)
        self.data_combo.setObjectName("data_combo")
        self.data_combo.addItem("")
        self.data_combo.addItem("")
        self.data_combo.addItem("")
        self.data_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.data_combo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.toolbar_layout = QtWidgets.QHBoxLayout()
        self.toolbar_layout.setObjectName("toolbar_layout")
        self.connection_box = QtWidgets.QGroupBox(self.tab_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_box.sizePolicy().hasHeightForWidth())
        self.connection_box.setSizePolicy(sizePolicy)
        self.connection_box.setStyleSheet("")
        self.connection_box.setFlat(False)
        self.connection_box.setObjectName("connection_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.connection_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.obc_ip_layout = QtWidgets.QHBoxLayout()
        self.obc_ip_layout.setObjectName("obc_ip_layout")
        self.obc_ip_label = QtWidgets.QLabel(self.connection_box)
        self.obc_ip_label.setObjectName("obc_ip_label")
        self.obc_ip_layout.addWidget(self.obc_ip_label)
        self.obc_ip_line_edit = QtWidgets.QLineEdit(self.connection_box)
        self.obc_ip_line_edit.setText("")
        self.obc_ip_line_edit.setObjectName("obc_ip_line_edit")
        self.obc_ip_layout.addWidget(self.obc_ip_line_edit)
        self.verticalLayout_4.addLayout(self.obc_ip_layout)
        self.obc_port_layout = QtWidgets.QHBoxLayout()
        self.obc_port_layout.setObjectName("obc_port_layout")
        self.obc_port_label = QtWidgets.QLabel(self.connection_box)
        self.obc_port_label.setObjectName("obc_port_label")
        self.obc_port_layout.addWidget(self.obc_port_label)
        self.obc_port_line_edit = QtWidgets.QLineEdit(self.connection_box)
        self.obc_port_line_edit.setText("")
        self.obc_port_line_edit.setObjectName("obc_port_line_edit")
        self.obc_port_layout.addWidget(self.obc_port_line_edit)
        self.verticalLayout_4.addLayout(self.obc_port_layout)
        self.obc_action_layout = QtWidgets.QHBoxLayout()
        self.obc_action_layout.setObjectName("obc_action_layout")
        self.connection_button = QtWidgets.QPushButton(self.connection_box)
        self.connection_button.setObjectName("connection_button")
        self.obc_action_layout.addWidget(self.connection_button)
        self.verticalLayout_4.addLayout(self.obc_action_layout)
        self.toolbar_layout.addWidget(self.connection_box)
        self.operations_box = QtWidgets.QGroupBox(self.tab_data)
        self.operations_box.setEnabled(False)
        self.operations_box.setFlat(False)
        self.operations_box.setCheckable(False)
        self.operations_box.setObjectName("operations_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.operations_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.get_data_button = QtWidgets.QPushButton(self.operations_box)
        self.get_data_button.setObjectName("get_data_button")
        self.verticalLayout_5.addWidget(self.get_data_button)
        self.clear_button = QtWidgets.QPushButton(self.operations_box)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout_5.addWidget(self.clear_button)
        self.toolbar_layout.addWidget(self.operations_box)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbar_layout.addItem(spacerItem3)
        self.export_box = QtWidgets.QGroupBox(self.tab_data)
        self.export_box.setEnabled(False)
        self.export_box.setObjectName("export_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.export_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.export_csv_button = QtWidgets.QPushButton(self.export_box)
        self.export_csv_button.setObjectName("export_csv_button")
        self.verticalLayout_2.addWidget(self.export_csv_button)
        self.export_xls_button = QtWidgets.QPushButton(self.export_box)
        self.export_xls_button.setObjectName("export_xls_button")
        self.verticalLayout_2.addWidget(self.export_xls_button)
        self.toolbar_layout.addWidget(self.export_box)
        self.verticalLayout_9.addLayout(self.toolbar_layout)
        self.tabWidget.addTab(self.tab_data, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.configure_stackedwidget.setCurrentIndex(-1)
        self.bus_combobox.currentIndexChanged['int'].connect(self.configure_stackedwidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MORE 2"))
        self.configure_box.setTitle(_translate("MainWindow", "Settings"))
        self.load_button.setText(_translate("MainWindow", "Load"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.start_button.setText(_translate("MainWindow", "Start test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MainWindow", "Test bench"))
        self.groupBox.setTitle(_translate("MainWindow", "Graph"))
        self.label.setText(_translate("MainWindow", "Displaying :"))
        self.data_combo.setItemText(0, _translate("MainWindow", "Temperature"))
        self.data_combo.setItemText(1, _translate("MainWindow", "Pressure"))
        self.data_combo.setItemText(2, _translate("MainWindow", "Acceleration"))
        self.data_combo.setItemText(3, _translate("MainWindow", "Payload"))
        self.connection_box.setTitle(_translate("MainWindow", "Connection"))
        self.obc_ip_label.setText(_translate("MainWindow", "OBC IP:"))
        self.obc_ip_line_edit.setPlaceholderText(_translate("MainWindow", "192.168.0.4"))
        self.obc_port_label.setText(_translate("MainWindow", "Port:"))
        self.obc_port_line_edit.setPlaceholderText(_translate("MainWindow", "9000"))
        self.connection_button.setText(_translate("MainWindow", "Connect"))
        self.operations_box.setTitle(_translate("MainWindow", "Operations"))
        self.get_data_button.setText(_translate("MainWindow", "Get data"))
        self.clear_button.setText(_translate("MainWindow", "Clear EEPROM"))
        self.export_box.setTitle(_translate("MainWindow", "Export"))
        self.export_csv_button.setText(_translate("MainWindow", "Export to .csv"))
        self.export_xls_button.setText(_translate("MainWindow", "Export to .xls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_data), _translate("MainWindow", "Data recovery"))

from mplcanvas import MplCanvas
